name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - name: Vue to Github Pages
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1

      with:
        username: 'matheusgomes062'
        reponame: 'vue-js-interview-study'
        token: ${{ secrets.GITHUB_TOKEN }}
